#![cfg_attr(not(feature = "std"), no_std)]

#[cfg(test)]
mod mock;

#[cfg(test)]
mod tests;

pub use pallet::*;

#[frame_support::pallet]
pub mod pallet {
	use frame_support::{pallet_prelude::*, BoundedVec};
	use frame_system::pallet_prelude::*;
	use sp_std::vec::Vec;

    // Structs for Sensory Data
    #[derive(Encode, Decode, Clone, PartialEq, Eq, RuntimeDebug, TypeInfo, MaxEncodedLen)]
    pub struct GeospatialData {
        pub lat: i32,  // Fixed point or raw integer
        pub long: i32, // Fixed point or raw integer
        pub alt: i32,  // Altitude in meters
    }

    #[derive(Encode, Decode, Clone, PartialEq, Eq, RuntimeDebug, TypeInfo, MaxEncodedLen)]
    pub struct AtmosphericData {
        pub temp: i32,      // Temperature in Celsius * 100
        pub humidity: u8,   // Humidity percentage (0-100)
        pub pressure: u32,  // Pressure in Pascals
    }

    #[derive(Encode, Decode, Clone, PartialEq, Eq, RuntimeDebug, TypeInfo, MaxEncodedLen)]
    pub struct TrustHeader<AccountId> {
        pub source: AccountId,
        pub signature: BoundedVec<u8, ConstU32<65>>, // Max signature length (e.g. 64 or 65 bytes)
        pub timestamp: u64,
    }

    // Unified State Struct for RPC
    #[derive(Encode, Decode, Clone, PartialEq, Eq, RuntimeDebug, TypeInfo)]
    pub struct NodeState<AccountId, Hash> {
        pub sensory_data: Vec<(GeospatialData, AtmosphericData, TrustHeader<AccountId>)>,
        pub conversational_proofs: Vec<Hash>, // List of vCon hashes owned/submitted by account
        pub ip_nfts: Vec<Hash>, // List of IP-NFT CIDs owned by account
    }

	#[pallet::pallet]
	pub struct Pallet<T>(_);

	#[pallet::config]
	pub trait Config: frame_system::Config {
		// RuntimeEvent is automatically generated by frame_support::pallet
	}

	// Storage Items
    #[pallet::storage]
    #[pallet::getter(fn sensory_readings)]
    pub type SensoryReadings<T: Config> = StorageMap<
        _,
        Blake2_128Concat,
        T::AccountId,
        BoundedVec<(GeospatialData, AtmosphericData, TrustHeader<T::AccountId>), ConstU32<100>>,
        ValueQuery
    >;

    #[pallet::storage]
    #[pallet::getter(fn conversational_proofs)]
    pub type ConversationalProofs<T: Config> = StorageMap<
        _,
        Blake2_128Concat,
        T::Hash,
        (T::AccountId, BlockNumberFor<T>),
        OptionQuery
    >;

    // Index mapping Account -> vCon Hashes for easy retrieval
    #[pallet::storage]
    #[pallet::getter(fn account_vcons)]
    pub type AccountVCons<T: Config> = StorageMap<
        _,
        Blake2_128Concat,
        T::AccountId,
        BoundedVec<T::Hash, ConstU32<100>>,
        ValueQuery
    >;

    #[pallet::storage]
    #[pallet::getter(fn ip_nft_ownership)]
    pub type IpNftOwnership<T: Config> = StorageMap<
        _,
        Blake2_128Concat,
        T::Hash,
        T::AccountId,
        OptionQuery
    >;

    // Index mapping Account -> IP-NFT CIDs for easy retrieval
    #[pallet::storage]
    #[pallet::getter(fn account_ip_nfts)]
    pub type AccountIpNfts<T: Config> = StorageMap<
        _,
        Blake2_128Concat,
        T::AccountId,
        BoundedVec<T::Hash, ConstU32<100>>,
        ValueQuery
    >;


	#[pallet::event]
	#[pallet::generate_deposit(pub(super) fn deposit_event)]
	pub enum Event<T: Config> {
		SensoryDataSubmitted { who: T::AccountId },
        VConProofSubmitted { who: T::AccountId, hash: T::Hash },
        ResearchAttested { who: T::AccountId, cid: T::Hash },
	}

	#[pallet::error]
	pub enum Error<T> {
		NoneValue,
		StorageOverflow,
        VConAlreadyExists,
        IpNftAlreadyExists,
	}

	#[pallet::call]
	impl<T: Config> Pallet<T> {

        #[pallet::call_index(0)]
		#[pallet::weight(10_000)]
		pub fn submit_sensory_data(
            origin: OriginFor<T>,
            lat: i32,
            long: i32,
            alt: i32,
            temp: i32,
            humidity: u8,
            pressure: u32,
            signature: BoundedVec<u8, ConstU32<65>>,
            timestamp: u64,
        ) -> DispatchResult {
			let who = ensure_signed(origin)?;

            let geo = GeospatialData { lat, long, alt };
            let atm = AtmosphericData { temp, humidity, pressure };

            let trust = TrustHeader {
                source: who.clone(),
                signature,
                timestamp,
            };

			SensoryReadings::<T>::try_mutate(&who, |readings| {
                readings.try_push((geo, atm, trust)).map_err(|_| Error::<T>::StorageOverflow)
            })?;

			Self::deposit_event(Event::SensoryDataSubmitted { who });
			Ok(())
		}

        #[pallet::call_index(1)]
        #[pallet::weight(10_000)]
        pub fn submit_vcon_proof(origin: OriginFor<T>, hash: T::Hash) -> DispatchResult {
            let who = ensure_signed(origin)?;

            ensure!(!ConversationalProofs::<T>::contains_key(hash), Error::<T>::VConAlreadyExists);

            let block_number = <frame_system::Pallet<T>>::block_number();
            ConversationalProofs::<T>::insert(hash, (&who, block_number));

            AccountVCons::<T>::try_mutate(&who, |vcons| {
                vcons.try_push(hash).map_err(|_| Error::<T>::StorageOverflow)
            })?;

            Self::deposit_event(Event::VConProofSubmitted { who, hash });
            Ok(())
        }

        #[pallet::call_index(2)]
        #[pallet::weight(10_000)]
        pub fn attest_research_data(origin: OriginFor<T>, cid: T::Hash) -> DispatchResult {
            let who = ensure_signed(origin)?;

            ensure!(!IpNftOwnership::<T>::contains_key(cid), Error::<T>::IpNftAlreadyExists);

            IpNftOwnership::<T>::insert(cid, &who);

            AccountIpNfts::<T>::try_mutate(&who, |nfts| {
                nfts.try_push(cid).map_err(|_| Error::<T>::StorageOverflow)
            })?;

            Self::deposit_event(Event::ResearchAttested { who, cid });
            Ok(())
        }
	}

    impl<T: Config> Pallet<T> {
        // Helper function for Unified RPC Getter logic
        pub fn get_node_state(who: T::AccountId) -> NodeState<T::AccountId, T::Hash> {
            let sensory_data = SensoryReadings::<T>::get(&who).into_inner();
            let conversational_proofs = AccountVCons::<T>::get(&who).into_inner();
            let ip_nfts = AccountIpNfts::<T>::get(&who).into_inner();

            NodeState {
                sensory_data,
                conversational_proofs,
                ip_nfts,
            }
        }
    }
}
